### ISSUE TITLE
Not compatible with Windows?   Illegal character in opaque part at index 2

### ISSUE THREAD

**Issue by danielmarschall** [icann/rdap-conformance-tool#13]
If I unter the command in Windows, I get following error message. It seems like a Windows path with double-colon and backslashes don't work.

```
D:\Test\rdap>java -jar rdapct-1.0.jar -c rdapct-config.json https://rdap.frdl.de/domain/frdl.de -v

22:16:44.843 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.RDAPValidator - Configuration is invalid
java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: D:\Test\rdap\rdapct-config.json
        at java.base/java.net.URI.create(URI.java:883)
        at org.icann.rdapconformance.validator.workflow.LocalFileSystem.uriToStream(LocalFileSystem.java:69)
        at org.icann.rdapconformance.validator.workflow.rdap.RDAPValidator.validate(RDAPValidator.java:111)
        at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:56)
        at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.icann.rdapconformance.tool.Main.main(Main.java:8)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: D:\Test\rdap\rdapct-config.json
        at java.base/java.net.URI$Parser.fail(URI.java:2913)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
        at java.base/java.net.URI$Parser.parse(URI.java:3120)
        at java.base/java.net.URI.<init>(URI.java:600)
        at java.base/java.net.URI.create(URI.java:881)
        ... 12 common frames omitted
```

**Comment by e-alvarez** [comment]
@danielmarschall Thank you for reporting this issue. This is an actual issue that will need a fix in the code to properly handle file paths when running in Windows. The main issue is that the OS uses backslash characters in file paths.

While we get a fix ready for this, you should be able to still run the tool by providing the configuration file parameter in the form of a URI. Using the file path and example you provided in your report, you can do this by enclosing the absolute path in double quotes, adding the scheme "**file://**" and replacing the backslash "\\" character with slash "/" characters. The full command would be a as follows:

`java -jar rdapct-1.0.jar -c "file:///D:/Test/rdap/rdapct-config.json" https://rdap.frdl.de/domain/frdl.de -v
`

Please let us know if this works for you.
