### ISSUE TITLE
rdap-json-values parsing error

### ISSUE THREAD

**Issue by shagren** [icann/rdap-conformance-tool#51]
Like as format/content of this file changed last days:
```
 docker run --rm rdapct3 -v https://rdap.verisign.com/com/v1/domain/manyxl.com 
16:03:48.678 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Dataset RDAPJSONValues is already downloaded
16:03:48.682 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset RDAPJsonValues
16:03:48.842 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Failed to parse dataset RDAPJSONValues
java.lang.IllegalArgumentException: No enum constant org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.JsonValueType.REDACTED_NAME
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues$JsonValueType.valueOf(RDAPJsonValues.java:42)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.parse(RDAPJsonValues.java:30)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset.parse(RDAPDataset.java:63)
	at org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService.download(RDAPDatasetService.java:83)
	at org.icann.rdapconformance.validator.workflow.rdap.RDAPValidator.validate(RDAPValidator.java:127)
	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:58)
	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.icann.rdapconformance.tool.Main.main(Main.java:8)
16:03:48.842 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService - Failed to parse dataset RDAPJSONValues

```

**Comment by shagren** [comment]
I have build fresh image from latest code few hours ago. But let's rebuild again:

```
shagren@wotan:~/tmp/rdap-conformance-tool$ git log -n1 | tee
commit 5eaa9321b4328df384f7c17c430e4271b951f9fb
Merge: 8a09d90 c29f438
Author: Andrew Newton <andy@hxr.us>
Date:   Fri May 31 13:31:17 2024 -0400

    Merge pull request #50 from Cobenian/cobenian-pr1
    
    expose the results file so we can read from it
shagren@wotan:~/tmp/rdap-conformance-tool$ docker build --no-cache -t rdapct3 .
Sending build context to Docker daemon   57.8MB
Step 1/21 : FROM alpine:latest
 ---> c059bfaa849c
Step 2/21 : RUN apk -q update ; apk -q add maven git jo
 ---> Running in b59111ea7462
Removing intermediate container b59111ea7462
 ---> 1339f85c7da7
Step 3/21 : WORKDIR /app
 ---> Running in 95bc324b104b
Removing intermediate container 95bc324b104b
 ---> 03319dbc2175
Step 4/21 : COPY . /app
 ---> 977356d5e88b
Step 5/21 : RUN mvn package -DskipTests --quiet
 ---> Running in e16cc9b77517
Removing intermediate container e16cc9b77517
 ---> ebe3bfd85359
Step 6/21 : RUN jo definitionIdentifier=test > config.json
 ---> Running in 241c89fb403c
Removing intermediate container 241c89fb403c
 ---> f8a58ee2f8e9
Step 7/21 : RUN mkdir datasets results
 ---> Running in c6f7e90caa85
Removing intermediate container c6f7e90caa85
 ---> 9731abafa5fd
Step 8/21 : ADD https://www.iana.org/assignments/rdap-extensions/rdap-extensions.xml datasets/rdap-extensions.xml
Downloading  8.998kB
 ---> 0db0bb4fc3c6
Step 9/21 : ADD https://www.iana.org/assignments/registrar-ids/registrar-ids.xml datasets/registrar-ids.xml
Downloading  557.1kB
 ---> 8086b5e60d4f
Step 10/21 : ADD https://data.iana.org/rdap/dns.json datasets/dns.json
Downloading   72.7kB
 ---> d3a1c4a95d18
Step 11/21 : ADD https://www.iana.org/assignments/epp-repository-ids/epp-repository-ids.xml datasets/epp-repository-ids.xml
Downloading  131.4kB
 ---> c840b00f8ee0
Step 12/21 : ADD https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xml datasets/iana-ipv4-special-registry.xml
Downloading  12.86kB
 ---> ba17404f4fa8
Step 13/21 : ADD https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.xml datasets/ipv4-address-space.xml
Downloading  76.33kB
 ---> 19d7c17cc215
Step 14/21 : ADD https://www.iana.org/assignments/link-relations/link-relations.xml datasets/link-relations.xml
Downloading   42.7kB
 ---> 53c00c48e512
Step 15/21 : ADD https://www.iana.org/assignments/rdap-json-values/rdap-json-values.xml datasets/rdap-json-values.xml
Downloading  45.92kB
 ---> 40850e3f2162
Step 16/21 : ADD https://www.iana.org/assignments/ipv6-address-space/ipv6-address-space.xml datasets/ipv6-address-space.xml
Downloading  9.646kB
 ---> 5bad15b816e0
Step 17/21 : ADD https://www.iana.org/assignments/ds-rr-types/ds-rr-types.xml datasets/ds-rr-types.xml
Downloading  2.281kB
 ---> 350852503b5a
Step 18/21 : ADD https://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xml datasets/dns-sec-alg-numbers.xml
Downloading  10.69kB
 ---> ba0507b13734
Step 19/21 : ADD https://www.iana.org/assignments/media-types/media-types.xml datasets/media-types.xml
Downloading  535.7kB
 ---> dc53b6d179b8
Step 20/21 : ADD https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xml datasets/iana-ipv6-special-registry.xml
Downloading  12.52kB
 ---> ffab279d59da
Step 21/21 : ENTRYPOINT ["./docker-entrypoint.sh"]
 ---> Running in 60b7534d5490
Removing intermediate container 60b7534d5490
 ---> 861cacda8871
Successfully built 861cacda8871
Successfully tagged rdapct3:latest
shagren@wotan:~/tmp/rdap-conformance-tool$ docker run --rm rdapct3 -v https://rdap.verisign.com/com/v1/domain/manyxl.com 
16:49:51.881 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Dataset RDAPJSONValues is already downloaded
16:49:51.884 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset RDAPJsonValues
16:49:52.057 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Failed to parse dataset RDAPJSONValues
java.lang.IllegalArgumentException: No enum constant org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.JsonValueType.REDACTED_NAME
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues$JsonValueType.valueOf(RDAPJsonValues.java:42)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.parse(RDAPJsonValues.java:30)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset.parse(RDAPDataset.java:63)
	at org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService.download(RDAPDatasetService.java:83)
	at org.icann.rdapconformance.validator.workflow.rdap.RDAPValidator.validate(RDAPValidator.java:127)
	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:58)
	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.icann.rdapconformance.tool.Main.main(Main.java:8)
16:49:52.057 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService - Failed to parse dataset RDAPJSONValues

```

Doesn't help :(

**Comment by anewton1998** [comment]
Ok. I just tried this with the latest commit and the one before and get the same issue. I don't know what broke and when, or even why this is a feature. We'll have to look into it. Thanks.

**Comment by j-bernard** [comment]
What is the command line in your entry point? Seems like you are still running an old version.

**Comment by shagren** [comment]
> What is the command line in your entry point? Seems like you are still running an old version.

Let's remove included docker entrypoint:
```
shagren@wotan:~/tmp/rdap-conformance-tool$ docker run -it --rm --entrypoint=/usr/bin/java rdapct3 -jar tool/bin/rdapct-1.0.jar -c config.json https://rdap.registry.com/domain/example.com -v
17:41:45.882 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset RDAPJSONValues
17:41:52.074 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset RDAPJsonValues
17:41:52.311 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Failed to parse dataset RDAPJSONValues
java.lang.IllegalArgumentException: No enum constant org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.JsonValueType.REDACTED_NAME
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues$JsonValueType.valueOf(RDAPJsonValues.java:42)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.parse(RDAPJsonValues.java:30)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset.parse(RDAPDataset.java:63)
	at org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService.download(RDAPDatasetService.java:83)
	at org.icann.rdapconformance.validator.workflow.rdap.RDAPValidator.validate(RDAPValidator.java:127)
	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:58)
	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.icann.rdapconformance.tool.Main.main(Main.java:8)
17:41:52.311 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService - Failed to parse dataset RDAPJSONValues
```

**Comment by shagren** [comment]
> What is the command line in your entry point? Seems like you are still running an old version.

I can remove whole docker:
```
shagren@wotan:~/tmp/rdap-conformance-tool$ java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment (build 17.0.11+9-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.11+9-Debian-1deb12u1, mixed mode, sharing)
shagren@wotan:~/tmp/rdap-conformance-tool$ mvn package -DskipTests --quiet
shagren@wotan:~/tmp/rdap-conformance-tool$ jo definitionIdentifier=test > config.json
shagren@wotan:~/tmp/rdap-conformance-tool$ java -jar tool/bin/rdapct-1.0.jar -c config.json https://rdap.registry.com/domain/example.com -v
20:47:30.938 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset RDAPJSONValues
20:47:34.407 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset RDAPJsonValues
20:47:34.576 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Failed to parse dataset RDAPJSONValues
java.lang.IllegalArgumentException: No enum constant org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.JsonValueType.REDACTED_NAME
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues$JsonValueType.valueOf(RDAPJsonValues.java:42)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.parse(RDAPJsonValues.java:30)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset.parse(RDAPDataset.java:63)
	at org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService.download(RDAPDatasetService.java:83)
	at org.icann.rdapconformance.validator.workflow.rdap.RDAPValidator.validate(RDAPValidator.java:127)
	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:58)
	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.icann.rdapconformance.tool.Main.main(Main.java:8)
20:47:34.576 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService - Failed to parse dataset RDAPJSONValues

```

**Comment by j-bernard** [comment]
Sorry, I didn't realize you were using the Dockerfile and entry point from the project. The entry point is using an old version of the tool.

**Comment by shagren** [comment]
Works for me, thxn!

But PR like as hack. 
I think will be better:
1. Remove `tool/bin/rdapct-1.0.jar` from repo
2. Build it via github actions and attach to release as artifact
3. Sync Readme, `Normal usage` topic refers to outdated jar. 

BTW you should add `datasets` folder to `.dockerignore` because after execution non-docker version (`java -jar tool/target/rdapct-1.0.4.jar --config config.json ...`) this folder will be created and `docker build` will be failed.

**Comment by jruppnamecom** [comment]
I am not running this in docker and just via my terminal.  I have re-downloaded the rdapct-1.0.jar file as well as the rdacpt-config.json and I am still getting the parsing issue.  

```
RDAP Conformance johnrupp$ java -jar rdapct-1.0.jar -c="./rdapct-config.json" --verbose --use-rdap-profile-february-2019 --gtld-registrar https://namerdap.systems/domain/testitems.world
14:56:53.264 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset linkRelations
14:56:54.450 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset LinkRelations
14:56:54.625 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset specialIPv6Addresses
14:56:54.690 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset SpecialIPv6Addresses
14:56:54.739 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset EPPROID
14:56:54.928 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset EPPRoid
14:56:55.462 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset ipv4AddressSpace
14:56:55.536 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset Ipv4AddressSpace
14:56:55.859 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset dnsSecAlgNumbers
14:56:55.936 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset DNSSecAlgNumbers
14:56:55.961 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset RDAPExtensions
14:56:56.034 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset RDAPExtensions
14:56:56.047 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset bootstrapDomainNameSpace
14:56:59.740 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset dsRrTypes
14:57:00.302 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset DsRrTypes
14:57:00.319 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset mediaTypes
14:57:00.779 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset MediaTypes
14:57:04.062 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset RDAPJSONValues
14:57:04.643 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset RDAPJsonValues
14:57:04.719 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Failed to parse dataset RDAPJSONValues
java.lang.IllegalArgumentException: No enum constant org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.JsonValueType.REDACTED_NAME
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues$JsonValueType.valueOf(RDAPJsonValues.java:42)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.parse(RDAPJsonValues.java:30)
	at org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset.parse(RDAPDataset.java:63)
	at org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService.download(RDAPDatasetService.java:83)
	at org.icann.rdapconformance.validator.workflow.rdap.RDAPValidator.validate(RDAPValidator.java:127)
	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:58)
	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.icann.rdapconformance.tool.Main.main(Main.java:8)
14:57:04.719 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService - Failed to parse dataset RDAPJSONValues
```

**Comment by anewton1998** [comment]
> Works for me, thxn!
> 
> But PR likes as hack. I think will be better:
> 
> 1. Remove `tool/bin/rdapct-1.0.jar` from repo
> 2. Build it via github actions and attach to release as artifact
> 3. Sync Readme, `Normal usage` topic still refers to outdated jar.
> 
> BTW you should add `datasets` folder to `.dockerignore` because after execution non-docker version (`java -jar tool/target/rdapct-1.0.4.jar --config config.json ...`) this folder will be created and `docker build` will be failed.

I agree. We'll work on it.

**Comment by anewton1998** [comment]
> I am not running this in docker and just via my terminal. I have re-downloaded the rdapct-1.0.jar file as well as the rdacpt-config.json and I am still getting the parsing issue.
> 
> ```
> RDAP Conformance johnrupp$ java -jar rdapct-1.0.jar -c="./rdapct-config.json" --verbose --use-rdap-profile-february-2019 --gtld-registrar https://namerdap.systems/domain/testitems.world
> 14:56:53.264 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset linkRelations
> 14:56:54.450 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset LinkRelations
> 14:56:54.625 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset specialIPv6Addresses
> 14:56:54.690 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset SpecialIPv6Addresses
> 14:56:54.739 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset EPPROID
> 14:56:54.928 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset EPPRoid
> 14:56:55.462 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset ipv4AddressSpace
> 14:56:55.536 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset Ipv4AddressSpace
> 14:56:55.859 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset dnsSecAlgNumbers
> 14:56:55.936 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset DNSSecAlgNumbers
> 14:56:55.961 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset RDAPExtensions
> 14:56:56.034 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset RDAPExtensions
> 14:56:56.047 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset bootstrapDomainNameSpace
> 14:56:59.740 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset dsRrTypes
> 14:57:00.302 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset DsRrTypes
> 14:57:00.319 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset mediaTypes
> 14:57:00.779 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset MediaTypes
> 14:57:04.062 [main] DEBUG org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Download dataset RDAPJSONValues
> 14:57:04.643 [main] INFO org.icann.rdapconformance.validator.workflow.rdap.dataset.model.XmlObject - Loading dataset RDAPJsonValues
> 14:57:04.719 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset - Failed to parse dataset RDAPJSONValues
> java.lang.IllegalArgumentException: No enum constant org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.JsonValueType.REDACTED_NAME
> 	at java.base/java.lang.Enum.valueOf(Enum.java:240)
> 	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues$JsonValueType.valueOf(RDAPJsonValues.java:42)
> 	at org.icann.rdapconformance.validator.workflow.rdap.dataset.model.RDAPJsonValues.parse(RDAPJsonValues.java:30)
> 	at org.icann.rdapconformance.validator.workflow.rdap.dataset.RDAPDataset.parse(RDAPDataset.java:63)
> 	at org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService.download(RDAPDatasetService.java:83)
> 	at org.icann.rdapconformance.validator.workflow.rdap.RDAPValidator.validate(RDAPValidator.java:127)
> 	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:58)
> 	at org.icann.rdapconformance.tool.RdapConformanceTool.call(RdapConformanceTool.java:22)
> 	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
> 	at picocli.CommandLine.access$1300(CommandLine.java:145)
> 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
> 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
> 	at picocli.CommandLine.execute(CommandLine.java:2078)
> 	at org.icann.rdapconformance.tool.Main.main(Main.java:8)
> 14:57:04.719 [main] ERROR org.icann.rdapconformance.validator.workflow.rdap.RDAPDatasetService - Failed to parse dataset RDAPJSONValues
> ```

@jruppnamecom The 1.0 jar won't work. You'll need to recompile with `mvn -DskipTests package` and execute the JAR file that creates. If you cannot do that, I suggest using the docker file.

**Comment by anewton1998** [comment]
I am closing this issue as the bug as been fixed.

**Comment by j-bernard** [comment]
> Works for me, thxn!
> 
> But PR likes as hack.

Yeah, this was a quick fix. But it was still better than taking an old bin that was not updated and building the tool for nothing in the Dockerfile :)
